In [18]:
from keras.models import Sequential
import numpy as np
from keras.layers.core import Dense
import tensorflow as tf
from sklearn.metrics import confusion_matrix
import pandas as pd
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

In [19]:
conjunto_datos = pd.read_csv('entrenamiento.csv', header=None, sep=',', skiprows=range(1))
datos_entrada = conjunto_datos.iloc[:,0:3].values
datos_salida = conjunto_datos.iloc[:,3:4].values

In [20]:
modelo = Sequential()
modelo.add(Dense(2, input_dim = 3,activation ='relu'))
modelo.add(Dense(1, activation = 'sigmoid'))
modelo.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['binary_accuracy'])
modelo.fit(datos_entrada, datos_salida, epochs = 500)

Epoch 1/500
7/7 [==============================] - 2s 9ms/step - loss: 0.9403 - binary_accuracy: 0.0200
Epoch 2/500
7/7 [==============================] - 0s 8ms/step - loss: 0.9255 - binary_accuracy: 0.0100
Epoch 3/500
7/7 [==============================] - 0s 6ms/step - loss: 0.9014 - binary_accuracy: 0.0150
Epoch 4/500
7/7 [==============================] - 0s 5ms/step - loss: 0.8611 - binary_accuracy: 0.0150
Epoch 5/500
7/7 [==============================] - 0s 7ms/step - loss: 0.7908 - binary_accuracy: 0.0150
Epoch 6/500
7/7 [==============================] - 0s 6ms/step - loss: 0.7017 - binary_accuracy: 0.0050
Epoch 7/500
7/7 [==============================] - 0s 5ms/step - loss: 0.5970 - binary_accuracy: 0.0050
Epoch 8/500
7/7 [==============================] - 0s 6ms/step - loss: 0.5114 - binary_accuracy: 0.4150
Epoch 9/500
7/7 [==============================] - 0s 6ms/step - loss: 0.4561 - binary_accuracy: 0.4950
Epoch 10/500
7/7 [==============================] - 0s 7ms/step 

7/7 [==============================] - 0s 4ms/step - loss: 0.0649 - binary_accuracy: 1.0000
Epoch 80/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0643 - binary_accuracy: 1.0000
Epoch 81/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0636 - binary_accuracy: 1.0000
Epoch 82/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0630 - binary_accuracy: 1.0000
Epoch 83/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0624 - binary_accuracy: 1.0000
Epoch 84/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0619 - binary_accuracy: 1.0000
Epoch 85/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0613 - binary_accuracy: 1.0000
Epoch 86/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0608 - binary_accuracy: 1.0000
Epoch 87/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0602 - binary_accuracy: 1.0000
Epoch 88/500
7/7 [==============================] - 0s 4ms/step - lo

7/7 [==============================] - 0s 4ms/step - loss: 0.0300 - binary_accuracy: 1.0000
Epoch 157/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0293 - binary_accuracy: 1.0000
Epoch 158/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0287 - binary_accuracy: 1.0000
Epoch 159/500
7/7 [==============================] - 0s 6ms/step - loss: 0.0281 - binary_accuracy: 1.0000
Epoch 160/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0274 - binary_accuracy: 1.0000
Epoch 161/500
7/7 [==============================] - 0s 14ms/step - loss: 0.0268 - binary_accuracy: 1.0000
Epoch 162/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0263 - binary_accuracy: 1.0000
Epoch 163/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0258 - binary_accuracy: 1.0000
Epoch 164/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0253 - binary_accuracy: 1.0000
Epoch 165/500
7/7 [==============================] - 0s 4ms

7/7 [==============================] - 0s 5ms/step - loss: 0.0029 - binary_accuracy: 1.0000
Epoch 234/500
7/7 [==============================] - 0s 6ms/step - loss: 0.0028 - binary_accuracy: 1.0000
Epoch 235/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0028 - binary_accuracy: 1.0000
Epoch 236/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0027 - binary_accuracy: 1.0000
Epoch 237/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0027 - binary_accuracy: 1.0000
Epoch 238/500
7/7 [==============================] - 0s 6ms/step - loss: 0.0026 - binary_accuracy: 1.0000
Epoch 239/500
7/7 [==============================] - 0s 4ms/step - loss: 0.0026 - binary_accuracy: 1.0000
Epoch 240/500
7/7 [==============================] - 0s 5ms/step - loss: 0.0025 - binary_accuracy: 1.0000
Epoch 241/500
7/7 [==============================] - 0s 7ms/step - loss: 0.0024 - binary_accuracy: 1.0000
Epoch 242/500
7/7 [==============================] - 0s 4ms/

7/7 [==============================] - 0s 6ms/step - loss: 7.5984e-05 - binary_accuracy: 1.0000
Epoch 309/500
7/7 [==============================] - 0s 5ms/step - loss: 7.4929e-05 - binary_accuracy: 1.0000
Epoch 310/500
7/7 [==============================] - 0s 5ms/step - loss: 7.3214e-05 - binary_accuracy: 1.0000
Epoch 311/500
7/7 [==============================] - 0s 4ms/step - loss: 7.2171e-05 - binary_accuracy: 1.0000
Epoch 312/500
7/7 [==============================] - 0s 5ms/step - loss: 7.0676e-05 - binary_accuracy: 1.0000
Epoch 313/500
7/7 [==============================] - 0s 7ms/step - loss: 6.9501e-05 - binary_accuracy: 1.0000
Epoch 314/500
7/7 [==============================] - 0s 5ms/step - loss: 6.8407e-05 - binary_accuracy: 1.0000
Epoch 315/500
7/7 [==============================] - 0s 6ms/step - loss: 6.7336e-05 - binary_accuracy: 1.0000
Epoch 316/500
7/7 [==============================] - 0s 5ms/step - loss: 6.5640e-05 - binary_accuracy: 1.0000
Epoch 317/500
7/7 [=====

7/7 [==============================] - 0s 5ms/step - loss: 2.9046e-05 - binary_accuracy: 1.0000
Epoch 383/500
7/7 [==============================] - 0s 5ms/step - loss: 2.8783e-05 - binary_accuracy: 1.0000
Epoch 384/500
7/7 [==============================] - 0s 5ms/step - loss: 2.8477e-05 - binary_accuracy: 1.0000
Epoch 385/500
7/7 [==============================] - 0s 5ms/step - loss: 2.8213e-05 - binary_accuracy: 1.0000
Epoch 386/500
7/7 [==============================] - 0s 5ms/step - loss: 2.8029e-05 - binary_accuracy: 1.0000
Epoch 387/500
7/7 [==============================] - 0s 5ms/step - loss: 2.7740e-05 - binary_accuracy: 1.0000
Epoch 388/500
7/7 [==============================] - 0s 4ms/step - loss: 2.7570e-05 - binary_accuracy: 1.0000
Epoch 389/500
7/7 [==============================] - 0s 5ms/step - loss: 2.7249e-05 - binary_accuracy: 1.0000
Epoch 390/500
7/7 [==============================] - 0s 5ms/step - loss: 2.7065e-05 - binary_accuracy: 1.0000
Epoch 391/500
7/7 [=====

7/7 [==============================] - 0s 6ms/step - loss: 1.6118e-05 - binary_accuracy: 1.0000
Epoch 457/500
7/7 [==============================] - 0s 5ms/step - loss: 1.6005e-05 - binary_accuracy: 1.0000
Epoch 458/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5838e-05 - binary_accuracy: 1.0000
Epoch 459/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5694e-05 - binary_accuracy: 1.0000
Epoch 460/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5580e-05 - binary_accuracy: 1.0000
Epoch 461/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5458e-05 - binary_accuracy: 1.0000
Epoch 462/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5372e-05 - binary_accuracy: 1.0000
Epoch 463/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5261e-05 - binary_accuracy: 1.0000
Epoch 464/500
7/7 [==============================] - 0s 5ms/step - loss: 1.5149e-05 - binary_accuracy: 1.0000
Epoch 465/500
7/7 [=====

In [21]:
p,b = modelo.layers[0].get_weights()
p2,b2 = modelo.layers[1].get_weights()
print(p, b)
x = [0, 102, 0]
#x = [997, 673, 823]
h1 = max(tf.keras.activations.relu(x[0]*p[0][0] + x[1]*p[1][0] + x[2]*p[2][0] + b[0]),0).numpy()
h2 = max(tf.keras.activations.relu(x[0]*p[0][1] + x[1]*p[1][1] + x[2]*p[2][1] + b[1]),0).numpy()
y = tf.keras.activations.sigmoid(h1*p2[0] + h2*p2[1] + b2[0]).numpy()
print(y)
print(y.round())
datos = modelo.evaluate(datos_entrada, datos_salida)
print("\n%s: %.2f%%" %(modelo.metrics[1], datos[1]*100))
y_pred = modelo.predict(datos_entrada).round()
print(y_pred)
y_pred = (y_pred >=.5)
cm = confusion_matrix(datos_salida, y_pred)
print(cm)

[[-0.7182563   0.90440464]
 [ 0.6299374  -0.83168924]
 [ 0.20556106  0.36057663]] [0.02498699 0.06496052]
[1.160483e-07]
[0.]
7/7 [==============================] - 1s 5ms/step - loss: 1.1997e-05 - binary_accuracy: 1.0000

MeanMetricWrapper(name=binary_accuracy,dtype=float32,fn=<function binary_accuracy at 0x0000020B9B542D30>): 100.00%
7/7 [==============================] - 0s 3ms/step
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]

In [22]:
p,b = modelo.layers[0].get_weights()
p2,b2 = modelo.layers[1].get_weights()
print(p, b)
print("----")
print(p2,b2)

[[-0.7182563   0.90440464]
 [ 0.6299374  -0.83168924]
 [ 0.20556106  0.36057663]] [0.02498699 0.06496052]
----
[[-0.23266414]
 [ 0.08955603]] [-1.013933]
